create table nongratas (
    id integer unique generated by default as identity not null,
    reason text not null,
    restriction_type text not null,
    restriction_value text not null,
    expires_at timestamptz not null,
    is_global boolean not null,
    primary key (id)
);
