create table if not exists nongratas (
    id bigint unique generated by default as identity not null,
    rule_id text not null,
    reason text not null,
    restriction_type text not null,
    restriction_value text not null,
    expires_at timestamptz not null,
    is_global boolean not null,
    analyzer_id text not null,
    primary key (id)
);

create index if not exists nongratas_restriction_value_rule_id_idx
on nongratas using btree (restriction_value, rule_id);
