create type filter_type as enum (
    'IP',
    'USER_AGENT',
    'IP_USER_AGENT'
);
create table if not exists filters (
    id text unique not null,
    rule_id text not null,
    filter_type filter_type unique not null,
    expression text not null,
    primary key (id)
);
create table if not exists nongratas (
    id int8 unique generated by default as identity not null,
    filter_id text references filters (id) not null,
    reason text not null,
    restriction_value text not null,
    restriction_type text not null,
    expires_at timestamptz not null,
    is_global boolean not null,
    analyzer_id text not null,
    primary key (id)
);
create index if not exists nongratas_restriction_value_filter_id_idx on filters using btree (expression, id);
